export { default as Navbar } from "./Navbar";
export { default as HeroSection } from "./HeroSection";
export { default as AboutSection } from "./AboutSection";
export {default as Status} from "./Status";
export {default as Paint} from "./Paint";
export {default as Loader} from "./Loader";
export {default as Feature} from "./Feature";
export {default as RecentProducts} from "./RecentProducts";
// export {default as Testinomial} from "./Testinomial";
export {default as Partener} from "./Partener" ;
export {default as Footer} from "./Footer";
export {default as Work} from "./Work";